exports.linkReplacements = {
  "https://www.gamma.co.uk/products/sip-trunking-call-management/": "https://gammagroup.co/products/sip-trunking-call-management/",
  "https://www.gamma.co.uk/products/business-phone-system/": "https://gammagroup.co/products/horizon-cloud-phone-system/",
  "https://www.gamma.co.uk/organisations/sme/": "https://gammagroup.co/solutions/",
  "https://www.gamma.co.uk/solutions/landline-replacement-pstn/": "https://gammagroup.co/solutions/pstn-switch-off/",
  "https://www.gamma.co.uk/products/": "https://gammagroup.co/products/",
  "https://www.gamma.co.uk/products/access/": "https://gammagroup.co/products/business-connectivity-broadband/",
  "https://www.gamma.co.uk/products/gamma-mobile/": "https://gammagroup.co/products/gamma-business-mobile/",
  "https://www.gamma.co.uk/organisations/public-sector/": "https://gammagroup.co/solutions/public-sector/",
  "https://www.gamma.co.uk/organisations/enterprise/": "https://gammagroup.co/solutions/enterprise-transformation/",
  "https://www.gamma.co.uk/resources/blog/the-sip-series-i-what-is-sip/": "https://gammagroup.co/resources/blog/the-sip-series-i-what-is-sip/",
  "https://www.gamma.co.uk/resources/blog/the-sip-series-ii-why-change-to-sip-trunks/": "https://gammagroup.co/resources/blog/the-sip-series-ii-why-change-to-sip-trunks/",
  "https://www.gamma.co.uk/resources/blog/the-sip-series-iii-how-do-i-replace-isdn/": "https://gammagroup.co/resources/blog/the-sip-series-iii-how-do-i-replace-isdn/",
  "https://www.gamma.co.uk/resources/blog/the-sip-series-iv-what-is-involved-in-sip-trunking/": "https://gammagroup.co/resources/blog/the-sip-series-iv-what-is-involved-in-sip-trunking/",
  "https://www.gamma.co.uk/resources/blog/the-sip-series-v-who-is-using-sip-trunking/": "https://gammagroup.co/resources/blog/the-sip-series-v-who-is-using-sip-trunking/",
  "https://www.gamma.co.uk/resources/blog/the-sip-series-vi-un-locking-your-data/": "https://gammagroup.co/resources/blog/the-sip-series-vi-un-locking-your-data/",
  "https://www.gamma.co.uk/solutions/business-voice/": "https://gammagroup.co/solutions/",
  "https://www.gamma.co.uk/solutions/unified-communications/": "https://gammagroup.co/solutions/unified-communications/",
  "https://www.gamma.co.uk/support/": "https://gammagroup.co/support/",
  // '': '',
};
